version:  '3'

services:
  api:
    image: node:14-alpine3.10
    container_name: node-marlon
    restart: always
    build: .
    command: npm start
    volumes: ['./:/usr/src/']
    ports:
      - '3333:3333'
    external_links:
      - mongodb
  mongodb:
    image: mongo:latest
    container_name: mongodb-marlon
    restart: always
    ports:
      - 27017:27017

