version:  '3'

services:
#  app:
#    image: node:12.19.0-alpine3.10
#    container_name: nodejs-backend
#    restart: always
#    command: npm run start
#    working_dir: /app
#    volumes:
#      - ./:/app
#    ports:
#      - 3333:3333
#    depends_on:
#      - mongodb
#    network_mode: host
  mongodb:
    image: mongo:latest
    command: [ --auth ]
    container_name: node-backend-marlon
    restart: always
    volumes:
      - ./.docker/mongo/data/:/data/db
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=mongopassw
      - MONGODB_USER=root
      - MONGODB_PASS=mongopassw
